services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=hospital_tracker
      - DB_SSLMODE=disable
      - REDIS_HOST=dragonfly
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - JWT_SECRET=your-very-secret-jwt-key-for-production
      - JWT_EXPIRE_HOURS=24
    depends_on:
      - postgres
      - dragonfly
    restart: unless-stopped
    networks:
      - hospital_network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hospital_tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - hospital_network

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.23.1
    volumes:
      - dragonfly_data:/data
    command: ["--alsologtostderr", "--bind", "0.0.0.0", "--port", "6379"]
    restart: unless-stopped
    networks:
      - hospital_network

volumes:
  postgres_data:
  dragonfly_data:

networks:
  hospital_network:
    driver: bridge